services:
  frontend:
    image: isongwuts/xams-frontend:1.5
    depends_on:
      - backend
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    networks:
      - xams-network

  backend:
    image: isongwuts/xams-backend:1.3
    depends_on:
      - mongo
    environment: 
      - DB_CONN=${DB_CONN}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_EXP=${ACCESS_TOKEN_EXP}
      - REFRESH_TOKEN_EXP=${REFRESH_TOKEN_EXP}
    ports:
      - "3000:3000"
    networks:
      - xams-network
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=isongwut
      - MONGO_INITDB_ROOT_PASSWORD=justapassword
    volumes:
      - mongo-data:/data/db
    networks:
      - xams-network

networks:
  xams-network:
    driver: bridge

volumes:
  mongo-data:
