services:
  frontend:
    image: isongwuts/xams-frontend:latest
    depends_on:
      - backend
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    networks:
      - xams-network

  backend:
    image: isongwuts/xams-backend:latest
    depends_on:
      - mongo
    environment:
      # Application Mode
      - MODE=${MODE:-prod}
      
      # Database Configuration
      - DB_CONN_LOCAL=${DB_CONN_LOCAL:-}
      - DB_CONN=${DB_CONN}
      
      # OpenRouter API (for AI features)
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      
      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_EXP=${ACCESS_TOKEN_EXP:-24h}
      - REFRESH_TOKEN_EXP=${REFRESH_TOKEN_EXP:-7d}
      
      # RSA Keys (if using RSA instead of JWT)
      - PUBLIC_KEY=${PUBLIC_KEY:-}
      - PRIVATE_KEY=${PRIVATE_KEY:-}
      
      # Email Configuration
      - EMAIL_HOST=${EMAIL_HOST:-}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USER=${EMAIL_USER:-}
      - EMAIL_PASS=${EMAIL_PASS:-}
    ports:
      - "3000:3000"
    networks:
      - xams-network
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=isongwut
      - MONGO_INITDB_ROOT_PASSWORD=justapassword
    volumes:
      - mongo-data:/data/db
    networks:
      - xams-network

networks:
  xams-network:
    driver: bridge

volumes:
  mongo-data:
