version: '3.8'
services:
  app:
    build:
      context: .
    image: xams-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["bun", "run", "src/index.ts"]
