FROM oven/bun:latest AS base
WORKDIR /usr/src/xams/backend

FROM base AS install
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

FROM install AS dev-deps
RUN mkdir -p /temp/dev
RUN cp -R node_modules /temp/dev

FROM install AS prod-deps
RUN mkdir -p /temp/prod
RUN bun install --frozen-lockfile --production && cp -R node_modules /temp/prod

FROM base AS prerelease
COPY --from=dev-deps /temp/dev/node_modules node_modules
COPY . . 
ENV NODE_ENV=production
RUN bun run build

FROM base AS release
COPY --from=prod-deps /temp/prod/node_modules node_modules
COPY . .

USER bun
EXPOSE 3000
ENTRYPOINT ["bun", "run", "src/index.ts"]
